import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, DM_Mono } from "next/font/google";
import { cn } from "@/lib/utils";
import Providers from "@/components/providers/providers";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import AppSidebar from "@/components/app-sidebar";
// import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import AppNav from "@/components/app-nav";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", dmSans.variable, dmMono.variable)}
      suppressHydrationWarning
    >
      <body>
        <SessionProvider>
          <Providers>
            <AppSidebar />
            <div className="flex min-w-0 min-h-0 flex-1 flex-col">
              <AppNav />
              <main className="flex min-w-0 min-h-0 flex-1 flex-col px-4 py-2">
                {children}
              </main>
            </div>
          </Providers>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
